package com.github.tommyettinger.colorful;

/**
 * Stores big lists of sprite names to be looked up in the atlas.
 * <br>
 * Created by Tommy Ettinger on 12/24/2019.
 */
public class DawnlikeData {
    public static final String[] possibleCharacters = {
            "ordinary human",
            "fighter",
            "ranger",
            "bandit",
            "valkyrie",
            "slayer",
            "wizard",
            "monk",
            "priest",
            "aide",
            "samurai",
            "collector",
            "brute",
            "nomad",
            "tourist",
            "convict",
            "man",
            "knight",
            "yeoman",
            "thief",
            "champion",
            "exterminator",
            "archmage",
            "sensei",
            "bishop",
            "healer",
            "ninja",
            "archaeologist",
            "barbarian",
            "caveman",
            "sightseer",
            "desperado",
            "ordinary woman",
            "priestess",
            "cavewoman",
    };
    public static final String[] possibleEnemies = {
            "frog",
            "baby plains chickabay",
            "plains chickabay",
            "baby fen chickabay",
            "fen chickabay",
            "baby taiga chickabay",
            "taiga chickabay",
            "baby doom chickabay",
            "doom chickabay",
            "baby nighthawk",
            "nighthawk",
            "baby cave swift",
            "cave swift",
            "baby arctic tern",
            "arctic tern",
            "baby robin",
            "robin",
            "baby osprey",
            "osprey",
            "baby phoenix",
            "phoenix",
            "baby aluminum falcon",
            "aluminum falcon",
            "baby cave penguin",
            "cave penguin",
            "baby penguin",
            "penguin",
            "baby pelican",
            "pelican",
            "baby duck",
            "duck",
            "baby puffin",
            "puffin",
            "baby swan",
            "swan",
            "baby albatross",
            "albatross",
            "baby condor",
            "condor",
            "baby green parrot",
            "green parrot",
            "baby dove",
            "dove",
            "baby parakeet",
            "parakeet",
            "baby thrush",
            "thrush",
            "baby cormorant",
            "cormorant",
            "baby seagull",
            "seagull",
            "baby bald eagle",
            "bald eagle",
            "golden eagle",
            "baby golden eagle",
            "baby ostrich",
            "ostrich",
            "baby emu",
            "emu",
            "baby kiwi",
            "kiwi",
            "chick",
            "hen",
            "rooster",
            "baby peacock",
            "peahen",
            "peacock",
            "baby griffon",
            "griffon",
            "baby snow griffon",
            "snow griffon",
            "baby barn owl",
            "barn owl",
            "baby snowy owl",
            "snowy owl",
            "white nosed bat",
            "giant bat",
            "vampire bat",
            "werebat",
            "baby bat",
            "baby gray parrot",
            "gray parrot",
            "bobcat",
            "leopard",
            "panther",
            "tiger",
            "lion",
            "puma kitten",
            "puma",
            "fierce puma",
            "lynx kitten",
            "lynx",
            "fierce lynx",
            "barn kitten",
            "barn cat",
            "fierce barn cat",
            "weretiger",
            "werecat",
            "barbed devil",
            "marilith",
            "vrock",
            "lava demon",
            "juiblex",
            "yeenoghu",
            "orcus",
            "geryon",
            "sandestin",
            "lesser devil",
            "pit fiend",
            "nalzok",
            "ixoth",
            "minion of huhetotl",
            "water demon",
            "mail daemon",
            "asmodeus",
            "baalzebub",
            "dispater",
            "erinys",
            "demogorgon",
            "cthulhu",
            "balrog",
            "bone devil",
            "ice devil",
            "horned devil",
            "homunculus",
            "manes",
            "lemure",
            "imp",
            "quasit",
            "succubus",
            "incubus",
            "derro slaver",
            "derro brute",
            "nalfeshnee",
            "hezrou",
            "jackal",
            "fox",
            "dingo",
            "coyote",
            "rabid jackal",
            "werejackal",
            "wolf",
            "warg",
            "baby winter wolf",
            "winter wolf",
            "rabid wolf",
            "werewolf",
            "little hound",
            "hound",
            "big hound",
            "little cogdog",
            "cogdog",
            "big cogdog",
            "little terrier",
            "terrier",
            "big terrier",
            "heck puppy",
            "hell hound",
            "cerberus",
            "straw golem",
            "paper golem",
            "wax golem",
            "rope golem",
            "gold golem",
            "leather golem",
            "wood golem",
            "flesh golem",
            "clay golem",
            "stone golem",
            "glass golem",
            "iron golem",
            "snow golem",
            "crystal golem",
            "fog cloud",
            "dust vortex",
            "ice vortex",
            "energy vortex",
            "steam vortex",
            "fire vortex",
            "stalker",
            "air elemental",
            "fire elemental",
            "earth elemental",
            "water elemental",
            "gas spore",
            "freezing sphere",
            "flaming sphere",
            "shocking sphere",
            "floating eye",
            "evil eye",
            "eye tyrant",
            "rock piercer",
            "iron piercer",
            "glass piercer",
            "small mimic",
            "large mimic",
            "giant mimic",
            "strange object",
            "xorn",
            "invisible creature",
            "lurker above",
            "lurker below",
            "yellow light",
            "black light",
            "giant",
            "stone giant",
            "hill giant",
            "fire giant",
            "frost giant",
            "storm giant",
            "ettin",
            "titan",
            "minotaur",
            "cyclops",
            "surtur",
            "keystone kop",
            "kop sergeant",
            "kop lieutenant",
            "kop kaptain",
            "shopkeeper",
            "executioner",
            "assassin",
            "prisoner",
            "forest sprite",
            "forest fairy",
            "forest spirit",
            "mountain sprite",
            "mountain fairy",
            "mountain spirit",
            "orc",
            "hill orc",
            "deep orc",
            "militant orc",
            "orc shaman",
            "orc king",
            "uruk",
            "soldier",
            "sergeant",
            "lieutenant",
            "captain",
            "watchman",
            "watch captain",
            "guard",
            "elf",
            "wood elf",
            "green elf",
            "gray elf",
            "elf lord",
            "elf king",
            "troll",
            "ice troll",
            "rock troll",
            "water troll",
            "olog hai",
            "gnome",
            "gnome lord",
            "gnome wizard",
            "gnome king",
            "leprechaun",
            "peasant man",
            "peasant woman",
            "farmer man",
            "farmer woman",
            "miner",
            "hobbit",
            "dwarf",
            "dwarf lord",
            "dwarf king",
            "wood nymph",
            "water nymph",
            "mountain nymph",
            "fire nymph",
            "quest leader a",
            "quest leader b",
            "quest leader c",
            "quest leader d",
            "satyr",
            "plains centaur",
            "forest centaur",
            "mountain centaur",
            "ogre",
            "ogre lord",
            "ogre king",
            "quantum mechanic",
            "croesus",
            "angel",
            "dark angel",
            "archon",
            "weeping angel",
            "weeping archangel",
            "tengu",
            "djinn",
            "marid",
            "dao",
            "goblin",
            "hobgoblin",
            "goblin king",
            "mind flayer",
            "master mind flayer",
            "bugbear",
            "yeti",
            "oracle",
            "nurse",
            "aligned priest",
            "high priest",
            "ocean spirit",
            "river spirit",
            "snow puff",
            "sand puff",
            "medusa",
            "rodent of unusual size",
            "ratzilla",
            "snowy owlbear",
            "owlbear",
            "spriggan",
            "pegasus",
            "kirin",
            "gremlin",
            "gargoyle",
            "winged gargoyle",
            "uranium imp",
            "kobold",
            "large kobold",
            "kobold shaman",
            "kobold lord",
            "monkey",
            "ape",
            "carnivorous ape",
            "jabberwock",
            "vorpal jabberwock",
            "umber hulk",
            "water hulk",
            "big hallucination",
            "small hallucination",
            "baby terror bird",
            "terror bird",
            "zruty",
            "giant tick",
            "giant flea",
            "giant louse",
            "giant beetle",
            "larva",
            "maggot",
            "dung worm",
            "tunnel worm",
            "walking stick",
            "dragonfly",
            "bee grub",
            "queen bee",
            "tsetse fly",
            "killer bee",
            "cave spider",
            "giant spider",
            "shelob",
            "scorpion",
            "giant scorpion",
            "scorpius",
            "baby long worm",
            "long worm",
            "long worm tail",
            "baby purple worm",
            "purple worm",
            "giant ant",
            "soldier ant",
            "fire ant",
            "snow ant",
            "firefly",
            "locust",
            "assassin bug",
            "grid bug",
            "xan",
            "chillbug",
            "baby slug",
            "giant slug",
            "baby snail",
            "giant snail",
            "spark bug",
            "arc bug",
            "phase spider",
            "centipede",
            "spitting beetle",
            "killer beetle",
            "evil shrub",
            "burning evil shrub",
            "demon shrub",
            "burning demon shrub",
            "blizzard shrub",
            "withered blizzard shrub",
            "maelstrom shrub",
            "withered maelstrom shrub",
            "evil tree",
            "burning evil tree",
            "demon tree",
            "burning demon tree",
            "blizzard tree",
            "withered blizzard tree",
            "maelstrom tree",
            "withered maelstrom tree",
            "dungeon fern",
            "dungeon fern sprout",
            "dungeon fern spore",
            "arctic fern",
            "arctic fern sprout",
            "arctic fern spore",
            "blazing fern",
            "blazing fern sprout",
            "blazing fern spore",
            "swamp fern",
            "swamp fern sprout",
            "swamp fern spore",
            "devil snare",
            "mould",
            "ungenomold",
            "shrieker",
            "baby pig",
            "pig",
            "baby hog",
            "hog",
            "feral hog",
            "baby black boar",
            "black boar",
            "vicious black boar",
            "baby dairy cow",
            "dairy cow",
            "baby bull",
            "bull",
            "raging bull",
            "camel",
            "llama",
            "baby white goat",
            "white goat",
            "baby gray goat",
            "gray goat",
            "baby black goat",
            "black goat",
            "baby white sheep",
            "white sheep",
            "baby gray sheep",
            "gray sheep",
            "baby black sheep",
            "black sheep",
            "brown unicorn",
            "white unicorn",
            "gray unicorn",
            "black unicorn",
            "newborn brown horse",
            "baby brown horse",
            "brown horse",
            "strong brown horse",
            "baby gray horse",
            "gray horse",
            "strong gray horse",
            "baby black horse",
            "black horse",
            "strong black horse",
            "baby deer",
            "deer",
            "mastodon",
            "mumak",
            "titanothere",
            "baluchitherium",
            "wumpus",
            "leocrotta",
            "baby sphinx",
            "sphinx",
            "baby wyvern",
            "wyvern",
            "baby dreadwyrm",
            "dreadwyrm",
            "baby glendrake",
            "glendrake",
            "baby firedrake",
            "firedrake",
            "baby icewyrm",
            "icewyrm",
            "baby sanddrake",
            "sanddrake",
            "baby stormwyrm",
            "storrmwyrm",
            "baby darkwyrm",
            "darkwyrm",
            "baby lightwyrm",
            "lightwyrm",
            "baby bogwyrm",
            "bogwyrm",
            "baby sheenwyrm",
            "sheenwyrm",
            "baby kingwyrm",
            "kingwyrm",
            "baby searwyrm",
            "searwyrm",
            "hydra",
            "baby hydra",
            "garter snake",
            "snake",
            "python",
            "water moccasin",
            "pit viper",
            "cobra",
            "asp",
            "serpent",
            "baby red naga",
            "red naga",
            "baby black naga",
            "black naga",
            "baby golden naga",
            "golden naga",
            "baby white naga",
            "white naga",
            "baby guardian naga",
            "guardian naga",
            "baby cockatrice",
            "cockatrice",
            "baby pyrolisk",
            "pyrolisk",
            "lizard",
            "iguana",
            "chameleon",
            "baby crocodile",
            "crocodile",
            "gecko",
            "komodo dragon",
            "gila monster",
            "newt",
            "giant turtle",
            "giant tortoise",
            "salamander",
            "red squirrel",
            "gray squirrel",
            "rabbit",
            "jackrabbit",
            "woodchuck",
            "sewer rat",
            "giant rat",
            "rabid rat",
            "enormous rat",
            "disintegrator",
            "rust monster",
            "rock mole",
            "wererat",
            "gray ooze",
            "brown pudding",
            "black pudding",
            "acid blob",
            "quivering blob",
            "gelatinous cube",
            "blue jelly",
            "spotted jelly",
            "ochre jelly",
            "green slime",
            "blue slime",
            "kobold zombie",
            "gnome zombie",
            "orc zombie",
            "dwarf zombie",
            "elf zombie",
            "human zombie",
            "ettin zombie",
            "giant zombie",
            "kobold mummy",
            "gnome mummy",
            "orc mummy",
            "dwarf mummy",
            "elf mummy",
            "human mummy",
            "ettin mummy",
            "giant mummy",
            "skeleton",
            "fire skeleton",
            "plague skeleton",
            "shadow skeleton",
            "lich",
            "demilich",
            "master lich",
            "archlich",
            "vampire",
            "vampire lord",
            "vampire mage",
            "vlad the impaler",
            "wisp",
            "spirit",
            "ghost",
            "shade",
            "death",
            "pestilence",
            "famine",
            "wraith",
            "nazgul",
            "barrow wight",
            "charon",
            "wizard of yendor",
            "war",
            "ghoul",
            "dark one",
            "meathead",
            "small meathead",
    };
}
